version: '3.7'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200/
    ports:
      - 5601:5601
    depends_on: ["elastic"]

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.11.0
    restart: on-failure
    user: root
    depends_on:
      - kibana
      - elastic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - metricbeat:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST=http://elastic:9200
      - KIBANA_HOST=http://kibana:5601

  locust-master:
    build: locust
    environment:
      - ELASTICSEARCH_HOST=http://elastic:9200
    ports:
      - "8080:8089"
    volumes:
      - ./locust:/mnt/locust
    command: "-f /mnt/locust/locustfile.py --tags ${LOCUST_TAGS:-light} --master -H http://locust-master:8089"

  locust-worker:
    build: locust
    volumes:
      - ./locust:/mnt/locust
    command: "-f /mnt/locust/locustfile.py --tags ${LOCUST_TAGS:-light} --worker --master-host locust-master"

  frontend-rr:
    image: symfony-demo:rr
    ports:
      - 8081:8080

  frontend-builtin:
    image: symfony-demo:builtin
    ports:
      - 8082:8080

  frontend-fpm:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx-fpm.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8083:8080
    depends_on:
      - fpm

  fpm:
    image: symfony-demo:fpm

  frontend-apache:
    image: symfony-demo:apache
    ports:
      - 8084:80

  rr:
    image: symfony-demo:rr

  frontend-rr-nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx-rr.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8085:8080
    depends_on:
      - rr

  frontend-ppm:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx-ppm.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8086:8080
    depends_on:
      - ppm

  ppm:
    image: symfony-demo:php-pm
    env_file:
      - .env
    environment:
      - APP_ENV=prod

volumes:
  esdata: ~
  metricbeat: ~
