version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8080:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    depends_on:
      - master

  frontend-rr:
    image: symfony-demo:rr
    ports:
      - 8081:8080

  frontend-builtin:
    image: symfony-demo:builtin
    ports:
      - 8082:8080

  frontend-fpm:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./docker/symfony-demo.conf:/etc/nginx/conf.d/default.conf
      - ./docker/upstream.conf:/etc/nginx/conf.d/upstream.conf
    ports:
      - 8083:8080
    depends_on:
      - fpm

  fpm:
    image: symfony-demo:fpm

  frontend-apache:
    image: symfony-demo:apache
    ports:
      - 8084:80
