metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 5s

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}"]

setup.dashboards:
  enabled: true

setup.kibana:
  host: "${KIBANA_HOST}"
